### ISSUE TITLE
support for NT 5.1

### ISSUE THREAD

**Issue by andika207** [QuickImageComment/QuickImageComment#10]
I have downloaded all 32-bit editions but neither of them runs on WinXP which supports NET 4.0

not sure why you make a NET 4.0 variant if you don't support older Windows editions (W7 and up do support any NET version)

**Comment by andika207** [comment]
![screenshot 12](https://user-images.githubusercontent.com/47242117/201782634-2bfb91cf-005e-46dc-999d-635b86d12cd8.png)

**Comment by norbertwg** [comment]
Thanks for your interest in QuickImageComment.
The last version running on Windows XP was 4.42. I have made it available again:
https://www.quickimagecomment.de/index.php/en/downloadview/20-32-bit-net-4-0/413-version-4-42-windows-xp

When I created 4.43, I noticed, that this was not running on Windows XP - with the error you posted. I tried to fix it, but I gave it up - assuming that there is no more interest in running it on Windows XP.  I continued to provide versions with .Net 4.0 as it was not much additional effort. To my own surprise, there was still interest in the version for .Net 4.0. The version 4.49 for .Net 4.0 was downloaded about 210 times. 
After moving to a new computer, I faced difficulties to install the development software to compile with .Net 4.0. Therefore I decided to stop supporting .Net 4.0. If there is a sufficient interest, I might try to investigate again on the Windows XP issue. And as long as my old computer is working, it would then be possible to provide versions running on Windows XP.

**Comment by norbertwg** [comment]
After making 4.42 available again, it was downloaded several times, so it seems, there is still some interest in Windows XP and I investgated, why 4.43 was not running on Windows XP. The reason: 4.43 was built with Visual Studio 2019, but for running on Windows XP, the C++ dll has to be built with Visual Studio 2017. With this knowledge it is not a big deal to support Windows XP again and the latest version 4.51 is available for Windows XP 32-bit with .Net 4.0:
https://www.quickimagecomment.de/index.php/en/downloadview/21-windows-xp-32-bit-net-4-0/418-version-4-51
